spring:
    application:
        name: report-ms
    jpa:
        show-sql: "true"
    profiles:
        default: default
    config:
        import: "optional:configserver:http://localhost:7777" #Config-server path

server:
    servlet:
        context-path: /report-ms
    port: 7070

eureka:
    instance:
        instance-id: "${spring.application.name}:${random.value}"
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/