spring:
    datasource:
        username: admin
        hikari:
            maximum-pool-size: 5
            connection-timeout: 20000
        url: jdbc:postgresql://localhost:5433/companies
        password: 1234
    application:
        name: companies
    jpa:
        show-sql: "true"

server:
    servlet:
        context-path: /companies-crud
    port: 8081

logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE

eureka:
    instance:
        instance-id: "${spring.application.name}:${random.value}"
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/